version: '3'
services:
  wxs:
    image: openquake/qgis-server:ltr
    environment:
      QGIS_USER: '${QGS_USER}'
    volumes:
      - ${QGS_DATA}:/io/data
    ports:
      - ${QGS_SERVER_PORT}:80
  plumber:
    build:
      context: .
      dockerfile: Dockerfile.plumber
    command: ['/opt/api.R']
    environment:
      FCT_DATA: /io/data
    volumes:
      - ${APP_ROOT}/plumber:/opt
      - ${FCT_DATA}:/io/data
    ports:
      - 3098:3098
  shiny:
    build:
      context: .
    user: shiny
    volumes:
      - ${APP_ROOT}/shiny:/srv/shiny-server/
      # - /var/log/shiny-server/:/var/log/shiny-server/
    ports:
      - 3838:3838