version: '3'
services:
  wxs:
    image: openquake/qgis-server:ltr
    environment:
      QGIS_USER: '${QGS_USER}'
    volumes:
      - ${QGS_DATA}:/io/data
    ports:
      - ${QGS_SERVER_PORT}:80
  plumber:
    image: fct-plumber
    environment:
      FCT_DATA: /io/data
    volumes:
      - ${FCT_DATA}:/io/data
    ports:
      - 3098:3098
  shiny:
    image: fct-shiny
    ports:
      - 3838:3838


